import { Inter } from 'next/font/google'
import { Crimson_Text } from 'next/font/google'
import { GeistSans } from 'geist/font/sans'
import type { Metadata } from 'next'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const crimsonText = Crimson_Text({ 
  weight: ['400', '600', '700'],
  subsets: ['latin'],
  variable: '--font-crimson-text'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={`${GeistSans.className} ${inter.variable} ${crimsonText.variable}`}
    >
      <body>{children}</body>
    </html>
  )
}
